export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS'
export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR'
export const PUSH_ITEM_TO_CART = 'PUSH_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
